name: Trigger auto deployment for container-app-2vd4lp7abeugk

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-2vd4lp7abeugk-AutoDeployTrigger-87d6c442-d277-4fea-98c6-f49daa5ce288.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP2VD4LP7ABEUGK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP2VD4LP7ABEUGK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP2VD4LP7ABEUGK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP2VD4LP7ABEUGK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP2VD4LP7ABEUGK_REGISTRY_PASSWORD }}
          containerAppName: container-app-2vd4lp7abeugk
          resourceGroup: appspacesragapp925ca397
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


